name: deafrica-water-quality-env
channels:
  - conda-forge
dependencies:
  # ODC ecosystem libraries
  - odc-loader
  - odc-stac
  # Code formatting
  - ruff
  - yamllint
  # Tests
  - coverage
  - pytest
  # Jupyter
  - jupytergis 
  - qgis
  - jupyterlab_iframe
  - jupyter-resource-usage
  - nodejs
  # Jupyter Ai
  - jupyter-ai
  - langchain-google-genai
  # developer tools
  - curl
  - make
  - wget
  - unzip
  # Do not use pip packages in environment file